07-lection4-checkbox
js-tasks-ru/htmlcss-20230411_gog3dgluhov pull request #20
Opened 2023-05-18 18:10 UTC by gog3d

2023-05-18 18:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-18 21:17 UTC, GSemikozov requested changes

2023-05-18 21:17 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +  cursor: pointer;
чтобы .checkbox__input не вываливался за пределы компонента, лучше еще добавить position: relative;

2023-05-19 14:50 UTC, GSemikozov approved these changes

2023-05-19 14:50 UTC, merged