07-lection4-toggler
js-tasks-ru/htmlcss-20230411_gog3dgluhov pull request #22
Opened 2023-05-18 20:00 UTC by gog3d

2023-05-18 20:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-18 21:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-18 21:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-18 21:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-18 21:20 UTC, GSemikozov requested changes

2023-05-18 21:20 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +  justify-contetnt: center;
см МР по чекбоксу

2023-05-18 21:20 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +  height: 27px;
28

2023-05-19 04:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-19 04:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-19 04:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-19 14:51 UTC, GSemikozov approved these changes

2023-05-19 14:51 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-05-19 14:52 UTC, GSemikozov approved these changes

2023-05-19 14:52 UTC, merged