add 04-lection2-histogram
js-tasks-ru/htmlcss-20230411_gog3dgluhov pull request #7
Opened 2023-04-29 21:05 UTC by gog3d

2023-04-29 21:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-01 12:16 UTC, GSemikozov requested changes

2023-05-01 12:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__block {
лишний элемент, можно просто удалить)

2023-05-01 12:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram-header {
.histogram__header

2023-05-01 12:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram-header__titles {
.histogram__titles

2023-05-01 12:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram-header__titles_title {
.histogram__title

2023-05-01 12:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram-header__titles_subtitle {
.histogram__subtitle

2023-05-01 12:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram-header__links {
.histogram__links

2023-05-01 12:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header__links_link {
.histogram__link

2023-05-01 12:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  padding: 39px 0px 0px 0px;
margin-top

2023-05-01 12:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram-group {
.histogram__chart

2023-05-01 12:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram-group_item {
.histogram__column / .histogram__chart-column

2023-05-04 14:28 UTC, GSemikozov approved these changes

2023-05-04 14:28 UTC, merged